setup/ncp: use recursive cp

diff --git a/setup/user/ncp b/setup/user/ncp
--- a/setup/user/ncp
+++ b/setup/user/ncp
@@ -3,8 +3,8 @@
 set -e
 
 if [[ -z "$*" ]]; then
-  echo "Not enough arguments"
-  exit 1
+	echo "Not enough arguments"
+	exit 1
 fi
 
 opts=$(getopt -o 'cd:' --long 'compatabilty,depth:' -n 'ncp' -- "$@")
@@ -12,36 +12,36 @@ opts=$(getopt -o 'cd:' --long 'compatabilty,depth:' -n 'ncp' -- "$@")
 DEPTH=1
 eval set -- "$opts"
 while :; do
-  case "$1" in
-  -d | --depth)
-    DEPTH="$2"
-    shift 2
-    ;;
-  -c | --compatability)
-    COMPMODE="true"
-    shift
-    ;;
-  --)
-    shift
-    break
-    ;;
-  *)
-    echo "Options error"
-    exit 1
-    ;;
-  esac
+	case "$1" in
+	-d | --depth)
+		DEPTH="$2"
+		shift 2
+		;;
+	-c | --compatability)
+		COMPMODE="true"
+		shift
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo "Options error"
+		exit 1
+		;;
+	esac
 done
 
 if [[ -z $2 ]]; then
-  echo "Not enough arguments"
-  exit 1
+	echo "Not enough arguments"
+	exit 1
 fi
 if [[ -n $3 ]]; then
-  echo "Too many arguments"
-  exit 1
+	echo "Too many arguments"
+	exit 1
 fi
 
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 PATH=$PATH:$SCRIPT_DIR
 echo "Copying $(format -d "$DEPTH" ${COMPMODE+"-c"} "$1") to $(format -d "$DEPTH" ${COMPMODE+"-c"} "$2")"
-cp "$1" "$2"
+cp -r "$1" "$2"
